### ISSUE TITLE
Feature request : RawInput support

### ISSUE THREAD

**Issue by ghost** [fabricecaruso/WiimoteGun#1]
The Mayflash Dolphinbar supports up to 4 controllers when using Mode 4 in a single Dolphinbar.
Potentially could be used to emulate multiple mice using RawInput with device indexes, I've successfully played in RetroBat (in Windows using this in game overrides:
```
input_driver = "raw"
input_player1_mouse_index = "0"
input_player2_mouse_index = "1"
```
Many Retroarch cores support multiple lightguns in Windows using RawInput, I've successfully tested RawInput (Sinden lightguns, Dolphinbar Mode 2, and mixed lightguns) with:
4DO
MAME
MAME 2003-Plus
FinalBurn Neo
MAME 2016
FB Alpha 2012
Flycast
FCEUmm
Genesis Plus GX
PCSX-ReARMed
Beetle Saturn (requires remapping Players 1 and 2 emulating different devices)
Snes9x

But then again the precision enhancements of the WiimoteGun are probably not designed to handle multiple cursors... I had a similar issue with the jitter enhancement in the Sinden software when testing multiple Sinden lightguns too (though these depend on their internal cameras filming the cursor).

References:
https://forums.libretro.com/t/configuring-ra-for-multi-mouse-spinners-lightguns-tackballs/12619
https://retropie.org.uk/docs/Spinners%2C-Trackballs%2C-Lightguns%2C-and-other-Mouse-Devices/

**Comment by fabricecaruso** [comment]
We already discussed this in private on Discord.
It's not possible unless you rewrite everything as a device driver.
WiimoteGun will always be "one player" only.
